[package]
name = "algorithms_of_deception"
version = "0.0.1"
authors = ["Zack M. Davis <code@zackmdavis.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
